{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 异常介绍\n",
    "**Scala 提供 try 块和 catch 块来处理异常**。try 块用于包含可能出错的代码。catch 块用于处理 try 块中发生的异常。可以根据需要在程序中有任意数量的 try…catch 块。\n",
    "\n",
    "语法处理上和 Java 类似，但是又不尽相同。"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Java 异常处理回顾\n",
    "示例代码如下：\n",
    "\n",
    "```java\n",
    "public class JavaExceptionDemo {\n",
    "    public static void main(String[] args) {\n",
    "        try {\n",
    "            // 可疑代码\n",
    "            int i = 0;\n",
    "            int b = 10;\n",
    "            int c = b / i; // 执行代码时，会抛出 ArithmeticException 异常\n",
    "        } catch (ArithmeticException e) {\n",
    "            e.printStackTrace();\n",
    "        } catch (Exception e) {//java中不可以把范围大的异常写在前面，否则报错！！\n",
    "            e.printStackTrace();\n",
    "        } finally {\n",
    "            // 最终要执行的代码\n",
    "            System.out.println(\"java finally\");\n",
    "        }\n",
    "\n",
    "        System.out.println(\"继续执行\");\n",
    "    }\n",
    "}\n",
    "```\n",
    "输出结果如下：\n",
    "```java\n",
    "java finally\n",
    "继续执行\n",
    "java.lang.ArithmeticException: / by zero\n",
    "    at com.atguigu.chapter05.exception.JavaExceptionDemo.main(JavaExceptionDemo.java:9)\n",
    "```\n",
    "\n",
    "**Java 异常处理的注意点：**\n",
    "\n",
    "* 1、java 语言按照 try-catch-catch…-finally 的方式来处理异常。  \n",
    "* 2、不管有没有异常捕获，都会执行 finally，因此通常可以在 finally 代码块中释放资源。  \n",
    "* 3、可以有多个 catch，分别捕获对应的异常，这时需要把范围小的异常类写在前面，把范围大的异常类写在后面，否则编译错误。会提示 \"Exception 'java.lang.xxxxxx' has already been caught\"。  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Scala 异常处理举例\n",
    "示例代码如下：\n",
    "```scala\n",
    "object ScalaExceptionDemo {\n",
    "  def main(args: Array[String]): Unit = {\n",
    "    try {\n",
    "      val r = 10 / 0\n",
    "    } catch {\n",
    "      // 说明\n",
    "      // 1. 在 scala 中只有一个 catch\n",
    "      // 2. 在 catch 中有多个 case, 每个 case 可以匹配一种异常\n",
    "      // 3. => 关键符号，表示后面是对该异常的处理代码块\n",
    "      // 4. finally 最终要执行的代码\n",
    "      case ex: ArithmeticException => { println(\"捕获了除数为零的算数异常\") } // 当对该异常的处理代码块为一行时，{}可以省略\n",
    "      case ex: Exception => println(\"捕获了异常\")\n",
    "    } finally {\n",
    "      // 最终要执行的代码\n",
    "      println(\"scala finally\")\n",
    "    }\n",
    "\n",
    "    System.out.println(\"继续执行\")\n",
    "  }\n",
    "}\n",
    "```\n",
    "\n",
    "输出结果如下：\n",
    "```\n",
    "捕获了除数为零的算数异常\n",
    "scala finally\n",
    "继续执行\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##  Scala 异常处理小结\n",
    "1、我们将可疑代码封装在 try 块中。在 try 块之后使用了一个 catch 处理程序来捕获异常。如果发生任何异常，catch 处理程序将处理它，异常处理了程序将不会异常终止。\n",
    "\n",
    "2、Scala 的异常的工作机制和 Java 一样，但是 Scala 没有“checked(编译期)” 异常，即 Scala 没有编译异常这个概念，异常都是在运行的时候捕获处理。\n",
    "\n",
    "3、Scala 用 throw 关键字，抛出一个异常对象。所有异常都是 Throwable 的子类型。throw 表达式是有类型的，就是 Nothing，因为 Nothing 是所有类型的子类型，所以 throw 表达式可以用在需要类型的地方。\n",
    "\n",
    "示例代码如下：\n",
    "```scala\n",
    "object ThrowDemo {\n",
    "  def main(args: Array[String]): Unit = {\n",
    "    // val res = test()\n",
    "    // println(res.toString)\n",
    "    // println(\"继续执行002\") // 异常抛出了，但是没有被处理，后续程序不能执行\n",
    "\n",
    "    // 如果我们希望在 test() 抛出异常后，后续代码可以继续执行，则我们需要如下处理\n",
    "    try {\n",
    "      test()\n",
    "    } catch {\n",
    "      case ex: Exception => {\n",
    "        println(\"捕获到异常是：\" + ex.getMessage)\n",
    "        println(\"继续执行001\")\n",
    "      }\n",
    "      case ex: ArithmeticException => println(\"得到一个算术异常（小范围异常）\")\n",
    "    } finally {\n",
    "      // 写上对 try{} 中的资源的分配\n",
    "    }\n",
    "\n",
    "    println(\"继续执行002\")\n",
    "  }\n",
    "\n",
    "  def test(): Nothing = {\n",
    "    // Exception(\"异常出现\")\n",
    "    throw new ArithmeticException(\"算术异常\")\n",
    "  }\n",
    "}\n",
    "```\n",
    "\n",
    "输出结果如下：\n",
    "```\n",
    "捕获到异常是：算术异常\n",
    "继续执行001\n",
    "继续执行002\n",
    "```\n",
    "\n",
    "4、**在 Scala 里，借用了模式匹配的思想来做异常的匹配**，因此，在 catch 的代码里，是一系列 case 子句来匹配异常。【前面案例可以看出这个特点，模式匹配我们后面详解】，当匹配上后 => 有多条语句可以换行写，类似 java 的 switch case x: 代码块…\n",
    "\n",
    "5、异常捕捉的机制与其他语言中一样，如果有异常发生，catch 子句是按次序捕捉的。因此，在 catch 子句中，越具体的异常越要靠前，越普遍的异常越靠后，如果把越普遍的异常写在前，把具体的异常写在后，在 scala 中也不会报错，但这样是非常不好的编程风格。\n",
    "\n",
    "6、finally 子句用于执行不管是正常处理还是有异常发生时都需要执行的步骤，一般用于对象的清理工作，这点和 Java 一样。\n",
    "\n",
    "7、Scala 提供了 throws 关键字来声明异常。可以使用方法定义声明异常。它向调用者函数提供了此方法可能引发此异常的信息。它有助于调用函数处理并将该代码包含在 try-catch 块中，以避免程序异常终止。在 scala 中，可以使用 throws 注释来声明异常。\n",
    "\n",
    "**与Java 不同，Scala 并不支持已被视为失败设计的检查型异常（checked exception）。Scala 将Java 中的检查型异常视为非检查型，而且方法声明中也不包含throws 子句。不过Scala 提供了有助于Java 互操作的@throws 注解。**\n",
    "\n",
    "示例代码如下：\n",
    "```scala\n",
    "object ThrowsComment {\n",
    "  def main(args: Array[String]): Unit = {\n",
    "    f()\n",
    "  }\n",
    "\n",
    "  @throws(classOf[NumberFormatException]) // 等同于 Java 中 NumberFormatException.class\n",
    "  def f() = {\n",
    "    \"abc\".toInt\n",
    "  }\n",
    "}\n",
    "```\n",
    "输出结果如下：\n",
    "```\n",
    "Exception in thread \"main\" java.lang.NumberFormatException: For input string: \"abc\"\n",
    "    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)\n",
    "    at java.lang.Integer.parseInt(Integer.java:580)\n",
    "    at java.lang.Integer.parseInt(Integer.java:615)\n",
    "    at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)\n",
    "    at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)\n",
    "    at com.atguigu.chapter05.exception.ThrowsComment$.f(ThrowsComment.scala:10)\n",
    "    at com.atguigu.chapter05.exception.ThrowsComment$.main(ThrowsComment.scala:5)\n",
    "    at com.atguigu.chapter05.exception.ThrowsComment.main(ThrowsComment.scala)\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Java检查型异常和非检查型异常\n",
    "### 检查型异常（CheckedException）\n",
    "在Java中**所有不是RuntimeException派生的Exception**都是检查型异常。当函数中存在抛出检查型异常的操作时该函数的函数声明中**必须包含throws语句**。调用改函数的函数也**必须对该异常进行处理**，如不进行处理则必须在调用函数上声明throws语句。\n",
    "\n",
    "检查型异常是JAVA首创的，在编译期对异常的处理有强制性的要求。在JDK代码中大量的异常属于检查型异常，包括IOException，SQLException等等。\n",
    "\n",
    "### 非检查型异常（UncheckedException）\n",
    "在Java中**所有RuntimeException的派生类**都是非检查型异常，与检查型异常对比，非检查型异常**可以不在函数声明中添加throws语句，调用函数上也不需要强制处理。**\n",
    "\n",
    "常见的NullPointException，ClassCastException是常见的非检查型异常。非检查型异常可以不使用try...catch进行处理，但是如果有异常产生，则异常将由JVM进行处理。**对于RuntimeException的子类最好也使用异常处理机制。虽然RuntimeException的异常可以不使用try...catch进行处理，但是如果一旦发生异常，则肯定会导致程序中断执行，所以，为了保证程序再出错后依然可以执行，在开发代码时最好使用try...catch的异常处理机制进行处理。**"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## scala异常处理比较综合的例子\n",
    "摘抄自《scala程序设计（第2版）》————3.9使用 try 、 catch 和 final 子句\n",
    "\n",
    "Scala 推崇通过使用函数式结构和强类型以减少对异常和异常处理的依赖的编码范式。尽管如此,异常仍然有用,而当 Scala 需要与普遍使用异常的 Java 代码交互时,异常尤为重要。\n",
    "\n",
    "**与Java 不同，Scala 并不支持已被视为失败设计的检查型异常（checked exception）。Scala 将Java 中的检查型异常视为非检查型，而且方法声明中也不包含throws 子句。不过Scala 提供了有助于Java 互操作的@throws 注解。**\n",
    "\n",
    "**Scala 将异常处理作为另一类模式匹配来进行处理,因此我们可以简洁地对各种不同类型的异常进行处理。**\n",
    "\n",
    "让我们看看 Scala 在资源管理这样一个常见的应用场景中是如何处理异常的。我们希望通过某种方式打开并处理一些文件。在这个示例中我们仅仅会统计行数。不过,我们仍然必须对一些错误场景进行处理。比如说,文件也许并不存在,这个错误尤其是当我们需要让用户指定文件名时尤为明显。除此之外,处理文件时可能也会有某些错误(为了测试错误发生的场景,我们将随意地触发一个错误)。无论是否成功地对文件进行了处理,我们都需要确保关闭了所有的文件句柄。\n",
    "\n",
    "```scala\n",
    "// src/main/scala/progscala2/rounding/TryCatch.scala\n",
    "package progscala2.rounding\n",
    "\n",
    "object TryCatch {\n",
    "  /** Usage: scala rounding.TryCatch filename1 filename2 ... */\n",
    "  def main(args: Array[String]): Unit = {\n",
    "    args foreach (arg => countLines(arg))                            // <1>\n",
    "  }\n",
    "\n",
    "  import scala.io.Source                                             // <2>\n",
    "  import scala.util.control.NonFatal\n",
    "\n",
    "  def countLines(fileName: String) = {                               // <3>\n",
    "    println()  // Add a blank line for legibility\n",
    "    var source: Option[Source] = None                                // <4>\n",
    "    try {                                                            // <5>\n",
    "      source = Some(Source.fromFile(fileName))                       // <6>\n",
    "      val size = source.get.getLines.size\n",
    "      println(s\"file $fileName has $size lines\")\n",
    "    } catch {\n",
    "      case NonFatal(ex) => println(s\"Non fatal exception! $ex\")      // <7>\n",
    "    } finally {\n",
    "      for (s <- source) {                                            // <8>\n",
    "        println(s\"Closing $fileName...\")\n",
    "        s.close\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "```\n",
    "\n",
    "➊ 使用 foreach 循环遍历参数列表并对各个参数进行处理。该循环每遍历一次便返回一个Unit 对象,而 foreach 执行完毕后所返回的最终结果也是 Unit 对象。  \n",
    "➋ 导 入 用 于 读 取 输 入 的 scala.io.Source 类以及用于匹配 nonfatal 异常的 scala.util.control.NonFatal 类。  \n",
    "➌ 统计每个文件名所对应文件的行数。  \n",
    "➍ 由 于 我 们 将 变 量 source 声 明 为 Option 类 型, 因 此 我 们 在 finally 子 句 中 能 分 辨 出source 对象是否是真正的实例。  \n",
    "➎ 开始执行 try 子句。  \n",
    "➏ 假如文件不存在, source.fromFile 方法将抛出 java.io.FileNotFoundException 类型的异常。否则的话,我们将该方法的返回值封装到 Some 对象中。下一行中我们将调用 source 变量的get方法,由于目前我们已经能确认 source 属于Some类型,因此这一操作是安全的。  \n",
    "➐ 捕获那些非致命的错误。例如,内存不足是一个致命错误。  \n",
    "➑ 使用 for 推导式从 Some 类型的对象中提取 Source 实例,之后将关闭文件。假如 source对象为 None ,将不会发生任何事。 \n",
    "\n",
    "请留意 catch 子句。Scala 会使用模式匹配来捕捉你所希望捕获的异常,而 Java 则使用单独的 catch 子句来捕获各个异常。与 Java 相比,Scala 捕获异常的方式更紧凑、更灵活。在这段示例代码中, case NonFatal(ex) => ... 子句使用 scala.util.control.NonFatal 匹配了所有的非致命性异常。\n",
    "\n",
    "应用 finally 子句可以确保资源会在一处得到合理的清理。如果不使用 finally ,我们将不得不分别在 try 子句和 catch 子句中重复清理逻辑,这样才能确保文件句柄会被关闭。由于我们使用了 for 推导式从 option 对象中抽取出 Source 对象,因此即使 option 对象实际上是一个 None 实例,什么也不会发生,包含了文件 close 方法的代码块并不会被调用。\n",
    "\n",
    "**假如你需要对 Option 对象进行检测,当它是 Some 对象时执行一些操作,而当它是 None 对象时则不进行任何操作,那么你可以使用 for 推导式,这也是 Scala 的一个广泛应用的常见用法。**\n",
    "\n",
    "由于该程序已经经过 sbt 编译,因此我们可以在 sbt 提示符后运行 run-main 任务来启动该程序,启动 run-main 任务时允许输入参数。为了方便阅读,我将输入参数折成多行,使用\\ 表示行符 ,并删除了一些文本。\n",
    "```\n",
    "> run-main progscala2.rounding.TryCatch foo/bar \\\n",
    "src/main/scala/progscala2/rounding/TryCatch.scala\n",
    "[info] Running rounding.TryCatch foo/bar .../rounding/TryCatch.scala\n",
    "... java.io.FileNotFoundException: foo/bar (No such file or directory)\n",
    "file src/main/scala/progscala2/rounding/TryCatch.scala has 30 lines\n",
    "Closing src/main/scala/progscala2/rounding/TryCatch.scala...\n",
    "[success] ...\n",
    "```\n",
    "第一个文件 foo/bar 并不存在,而第二个文件才是该程序的源文件。使用 scala.io.SourceAPI 能够方便地对来自文件或其他源的数据流进行处理。与一些这类的 API 相似,文件不存在时 Source 将抛出异常。因此读取 foo/bar 文件时抛出异常的行为是可预期的行为。\n",
    "\n",
    "**假如无论是否成功地使用了资源,资源都需要被清理,请将资源清理的相关逻辑放到 finally 子句中执行。**\n",
    "\n",
    "除了使用模式匹配定位异常之外,Scala 异常处理的其他设定与大多数语言相似。与 Java一样,使用 Scala 时我们通过编写 throw new MyBadExceptoin(...) 抛出异常。假如你自定义的异常是一个 case 类,那么抛出异常时可以省略 new 关键字。这就是 Scala 与其他语言在异常处理上的差别。"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Scala 2.11.11",
   "language": "scala",
   "name": "scala"
  },
  "language_info": {
   "codemirror_mode": "text/x-scala",
   "file_extension": ".scala",
   "mimetype": "text/x-scala",
   "name": "scala211",
   "nbconvert_exporter": "script",
   "pygments_lexer": "scala",
   "version": "2.11.11"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": true
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
